### ISSUE TITLE
jager trace cli and catch error 

### ISSUE THREAD

**Issue by haitham911** [k8-proxy/go-k8s-process#101]
jager must trace cli and catch error from rebuild files

**Comment by Lestat06** [comment]
this is confirmed in dev branch
![image](https://user-images.githubusercontent.com/6232283/125318104-d6b8ac00-e339-11eb-9527-4921db068ec1.png)
![image](https://user-images.githubusercontent.com/6232283/125318259-fc45b580-e339-11eb-8d18-1817e1b5d2dd.png)
