### ISSUE TITLE
fail run go-k8s-process docker 

### ISSUE THREAD

**Issue by haitham911** [k8-proxy/go-k8s-process#25]
when I run docker
docker: Error response from daemon: pull access denied for test-adp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by ibrahimk9000** [comment]
this seem like problem in docker configuration , not the Dockerfile

**Comment by haitham911** [comment]
so how I can fix docker configuration

**Comment by GINAGC** [comment]
this is done
