### ISSUE TITLE
Burstable processing pods configuration

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/go-k8s-process#38]

**Comment by kekesimarti** [comment]
@GINAGC or @mahnouman please share the technical details needed for @himanshu2464 to solve this issue. Thank you.

**Comment by himanshu2464** [comment]
i need more technical details in order to solve the issues.

**Comment by himanshu2464** [comment]
@GINAGC  
from what i understood fro request is to configure the go-k8s-process with Kubernetes QoS class Brustable by adding resource request and limits to the deployment of go-k8s-process.

**Comment by mahnouman** [comment]
Hi @himanshu2464 , the idea is to allow the pod to use more resources that is assigned to it if there is a room for that, not sure in Kubernetes world what this would be like, but for example in networking you can assign a traffic class a guaranteed ( reserved ) bandwidth of 2 Mbps but allow it to burst to 5 Mbps if there is a room for that, i.e. the link is not congested. Same idea here but for resources

**Comment by himanshu2464** [comment]
yes in Kubernetes we have 3 classes, Guaranteed, Burstable, and BestEffort where we can define the resource limit and request. 

this can be achieved in Kubernetes as well but i need to know more information regarding the request and limits of the resource assign to pods.

**Comment by GINAGC** [comment]
@haitham911 assigning to you to verify the code: https://github.com/k8-proxy/go-k8s-controller/tree/burst_config
