### ISSUE TITLE
Copy the log file to MinIO

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/go-k8s-process#41]
@kekesimarti commented on [Fri May 07 2021](https://github.com/k8-proxy/go-k8s-srv/issues/12)

**Comment by GINAGC** [comment]
@samarthdd I will share a demo meeting for this one.

**Comment by samarthdd** [comment]
@ibrahimk9000

**Comment by samarthdd** [comment]
I tried ssh -L 9000:127.0.0.1:9001 -i <key_pair> centos@54.216.145.139

But minio is not available

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/120392084-a00c7080-c34d-11eb-8a26-f8ef633719b6.png)
![image](https://user-images.githubusercontent.com/64204445/120392093-a26eca80-c34d-11eb-897c-100dea3955ec.png)

This has been tested

Minio is not avaialble directly with port mapping


Workaround to test is

`kubectl edit svc minio-server -n minio`
change ClusterIp to LoadBalancer

then check TCP port in `kubectl get svc -n minio` and open that port

**Comment by samarthdd** [comment]
Few observations
cleanfiles folder has

metadata  json
log
gw.log
rebuild file
rebuild xml

**Comment by samarthdd** [comment]
Metadata Json looks good

![image](https://user-images.githubusercontent.com/64204445/120392688-76077e00-c34e-11eb-99e4-0e08b68f7a07.png)

**Comment by samarthdd** [comment]
file name is replaced with file-id ( like 710b78fb-bc16-4e5e-bbb7-98937c035555 )

**Comment by samarthdd** [comment]
@ibrahimk9000 @GINAGC 

I have observed 3 changes observed from meeting recording

First one is the folder structure should be like this

cleanfiles
  - file-id folders
         - metadata.json
         - report.xml
         - rebuild
         - log
         - gw.log

Second one, do we need to allow minio to be accessed outside using ssh??. if so I have posted workaround above which needs to be present in AMI

Third one - zip file processing, all these folders which are zip files should have .zip extension

![image](https://user-images.githubusercontent.com/64204445/120394084-92a4b580-c350-11eb-884c-542b85b2fdd4.png)

**Comment by ibrahimk9000** [comment]
i added the minio folder structure suggestions , i will send pull request today

**Comment by mahnouman** [comment]
@Lestat06 @samarthdd that is fixed in:
https://github.com/k8-proxy/go-k8s-process/pull/64
