### ISSUE TITLE
 Start supporting content management from the Cloud SDK, which can be done in the minio version.

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/go-k8s-process#49]
Start supporting content management from the Cloud SDK, which can be done in the minio version.
See [https://engineering.glasswallsolutions.com/docs/products/cloud-sdk/rebuild/rebuild-content-management](https://engineering.glasswallsolutions.com/docs/products/cloud-sdk/rebuild/rebuild-content-management)
The idea is to first get the architecture for this design. 
Take a look at the code samples we have provided and how the API used on [file-drop.co.uk](file-drop.co.uk) works

**Comment by Lestat06** [comment]
this is a great feature now.
case 1
in the below case tried #2(disallow) policy and the file didnt get processed
![image](https://user-images.githubusercontent.com/6232283/123938934-e1695d80-d997-11eb-8238-b6dc14c3e9a7.png)
![image](https://user-images.githubusercontent.com/6232283/123938973-ededb600-d997-11eb-95cd-4591a93131f9.png)
![image](https://user-images.githubusercontent.com/6232283/123939005-f80fb480-d997-11eb-907c-84e3be7e7f53.png)

case 2
disallowed only METADA and put a docx with metada inside. OUTPUT: GW_UNPROCESSABLE

case 3 (0 allow)
file could be downloaded. downloads original file with Glasswall watermark( unclean)

case 4 (disallow javasript)
pdf file with javascript inside didnt get processed

case 5 endpoint `/api/rebuild/zipfile`  metadata -disallow
put a zip file containing 
1 clean file
2 file with issues
1 file with metadata
OUTPUT: a zip file only with the clean file inside

Case 6    endpoint `/api/rebuild/zipfile`  policy sanitize all
put a zip file containing 
1 clean file
2 file with issues
1 file with metadata
OUTPUT: a zip file with:
1 clean file
1 file with metada (cleaned)

in report.xml for pdf file there are 2 policies that are not included for user to change
![image](https://user-images.githubusercontent.com/6232283/123946914-0530a180-d9a0-11eb-91a6-5a11c2aa9cdd.png)
FYI @GINAGC

**Comment by ibrahimk9000** [comment]
@Lestat06 
the value_outside_resonable_limits and retain_exported_stream are not in the content management policy in this documentary :
https://engineering.glasswallsolutions.com/docs/products/cloud-sdk/rebuild/rebuild-content-management

**Comment by Lestat06** [comment]
correct than this is ok. thank you

**Comment by samarthdd** [comment]
Tested below cases for all APIs

watermark
allow ( 0 ) - ,this doesnt remove any headers as expected and can be rebuilt from filedrop 
sanitize ( 1 ) - ok and clean file
disallow - getting "rebuildProcessingStatus": "UNPROCESSABLE" - ok

/api/rebuild/file
/api/rebuild/base64
/api/rebuild/zipfile
     if i give 2 ( disallow ) for pdfs, it neglects pdfs and send only other files
/api/analyse/base64
/api/SDK/rebuild-zip-from-base64
/api/analyse/rebuild-zip-from-base64
/api/analyse/rebuild-zip-from-file


Issues :
1.

for below API , content management is not working 
/api/SDK/rebuild-zip-from-file

If i give below policy, it should say Unprocessed. But its rebuilding file

"PdfContentManagement": {
        "Acroform": 2,
        "ActionsAll": 2,
        "EmbeddedFiles": 2,
        "EmbeddedImages": 2,
        "ExternalHyperlinks": 2,
        "InternalHyperlinks": 2,
        "Javascript": 2,
        "Metadata": 2,
        "Watermark": "Glasswall T"
      },


2.

/api/filetypedetection/base64 is not working

{
  "errors": [
    "Input file could not be decoded from base64."
  ]
}

Also why do we need content management polict for this API?

**Comment by samarthdd** [comment]
Please confirm these can not be set from content policy

value_outside_reasonable_limits
retain_exported_streams
digital_signatures

**Comment by ibrahimk9000** [comment]
@samarthdd 
yes , i confirm , i followed this schema for the content management policy
https://engineering.glasswallsolutions.com/docs/products/cloud-sdk/rebuild/rebuild-content-management
