### ISSUE TITLE
Office suite files are being detected as zip files

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-process#73]
Seems that office files which ends with x, like .docx or .xlsx are being identified as zip files and hence treated accordingly, retuning a zipped report which cause the API to throw an error.

Possible relevant Stackoverflow article:
https://stackoverflow.com/questions/29838185/how-to-detect-additional-mime-type-in-golang

**Comment by GINAGC** [comment]
@haitham911, @mahnouman is this fixed?

**Comment by GINAGC** [comment]
@Lestat06 can we close this one? it was fixed on latest release.

**Comment by Lestat06** [comment]
@GINAGC yes this is fixed
