### ISSUE TITLE
Review Content Management Policy PR

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-process#78]
Review this PR please and make sure that it is not interfering with the existing code in develop branch,
https://github.com/k8-proxy/go-k8s-process/pull/77

**Comment by haitham911** [comment]
I reviewed the code by running the test but I always get this error
rebuild status is  : INTERNAL ERROR
{"level":"error","error":"exit status 1","time":"2021-06-20T03:16:07+02:00","message":"error failed to rebuild file"}
{"level":"info","Exchange":"processing-outcome-exchange","RoutingKey":"processing-outcome","time":"2021-06-20T03:16:07+02:00","message":"message published to queue "}

**Comment by mahnouman** [comment]
Feedback has been created as another issue #88 , this one is safe to close.
