### ISSUE TITLE
Fix issue on metada.json that define office type as zip file

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/go-k8s-process#87]

**Comment by GINAGC** [comment]
@ibrahimk9000 for the issue that we just talked about.

**Comment by GINAGC** [comment]
@samarthdd and @Lestat06 this fix is only about reporting in the metadata.json that the office files are office.

**Comment by Lestat06** [comment]
tested with different files and saw the metadata.json inside minio
.DOCM-->"FileType": "zip",
.DOC-->"FileType": "octet-stream",
.PDF-->"FileType": "pdf",
.DOCX-->"FileType": "zip",
tested from this run from flavor:golang and branch:develop

**Comment by ibrahimk9000** [comment]
can you give me these sample files you used in the testing

**Comment by Lestat06** [comment]
@ibrahimk9000 will share in slack since some are not supported in here

**Comment by GINAGC** [comment]
@Lestat06 so this one should be back to dev?

**Comment by ibrahimk9000** [comment]
yes
 and i  will add other option for  the supported files in the glasswall engine , if the file type is not supported it will be "unsupported  content type "  in the metadata file

**Comment by ibrahimk9000** [comment]
due the latest changes , the file type now is extracted from the report file , so you can compare the fileType field in metadata.json with <gw:FileType> element in report file

**Comment by Lestat06** [comment]
kept notes for this while testing the policy management
DOCM--> "FIletype: docx"
DOC--> "Filetype: doc
DOCX-->"FileType": "docx"
PDF-->"FileType": "pdf"
XLSM-->"FileType": "xlsx"
PPT-->"FileType": "ppt",
ZIP-->"FileType": "zip",
some are not quite exact but at least it defines that is from same family

**Comment by samarthdd** [comment]
as @Lestat06 said this is not fixed, still getting zip for office files

**Comment by GINAGC** [comment]
@ibrahimk9000, is there anything that we can do for the DOCM and XLSM, or that is the way you get the info?

these are the outputs i got
DOCM--> "FIletype: docx"
DOC--> "Filetype: doc
DOCX-->"FileType": "docx"
PDF-->"FileType": "pdf"
XLSM-->"FileType": "xlsx"
PPT-->"FileType": "ppt",
ZIP-->"FileType": "zip",

**to conclude, office files are not defined as zip anymore.**
 however
DOCM is define as docx
XLSM is defined as xlsx

**Comment by ibrahimk9000** [comment]
@GINAGC 
i can't do anything for these cases , these filetype result are from the glasswall engine
there will be always some odd files that there content type will not be detected correctly
