### ISSUE TITLE
INTERNAL ERROR always returned when running test

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-process#88]
By running the test always received this error on screen:
rebuild status is : INTERNAL ERROR
{"level":"error","error":"exit status 1","time":"2021-06-20T03:16:07+02:00","message":"error failed to rebuild file"}
{"level":"info","Exchange":"processing-outcome-exchange","RoutingKey":"processing-outcome","time":"2021-06-20T03:16:07+02:00","message":"message published to queue "}

![image](https://user-images.githubusercontent.com/5932628/122755340-281ecf80-d295-11eb-9ffb-0ed6c83707d1.png)

Seems the test code is not going through the rebuild process, can you please redo the test locally and check if the same or what is needed to modify the test inputs in order to make the code loop through the file processing part of the code.

**Comment by mahnouman** [comment]
@ibrahimk9000 Codecov test is failing after merge

**Comment by mahnouman** [comment]
Notes: add mutex to rabbitmq header variable to prevent racing

**Comment by mahnouman** [comment]
@haitham911 please check

**Comment by Lestat06** [comment]
@GINAGC I cant test this since its as per what Ibrahim explained to me this is just a unit test  that is not related to the final product and it doesnt impact it
