### ISSUE TITLE
go-k8s-process testing

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-process#9]
Please build and test the code in this repo as per the instructions in the readme file, please take note of missing steps or whenever you get stuck.

**Comment by ibrahimk9000** [comment]
the cmd seem dependent on  dotnet to run C# rebuild engine  this line : 
https://github.com/k8-proxy/go-k8s-process/blob/9592f87687730036afa2217164b77213810588ff/cmd/main.go#L139

but the dockerfile doesn't contain Dotnet build nor rebuild engine

**Comment by ibrahimk9000** [comment]
the app quit and throw error when it trying to rebuild file
so the k8-srv1 send message with minio file url , and then  k8-process  download the file and when it try rebuild it  , it throw error " signal: aborted (core dumped)"   and quit 
screenshot
![Screenshot from 2021-04-01 10-30-58 (1)](https://user-images.githubusercontent.com/37180689/113276488-c7a47580-92d7-11eb-9a59-31eb91db746c.png)

**Comment by mahnouman** [comment]
Hello @mohammedbakr ,, please test the new code developed by @ibrahimk9000 currently in develop branch.

**Comment by mohammedbakr** [comment]
It worked and received the rebuild file with GW watermark on it
