### ISSUE TITLE
change the content management policy to accept watermark

### ISSUE THREAD

**Issue by ibrahimk9000** [k8-proxy/go-k8s-process#91]
change  the k8-processs content management policy to process watermark attribute  like this 

if there is watermark attribute like "Watermark": "Processed" it will show the "Processed" watermark on the pdf file

if the watermark attribute is empty like "Watermark": "" or the watermark attribute is not present then the processed pdf file will not have any watermark

**Comment by Lestat06** [comment]
confirmed
 "Watermark": "glasswall"
![image](https://user-images.githubusercontent.com/6232283/123962136-6876ff80-d9b1-11eb-87b7-230ca9557951.png)

"Watermark": ""
![image](https://user-images.githubusercontent.com/6232283/123962240-86446480-d9b1-11eb-9998-b8dfbf1113d8.png)

**Comment by samarthdd** [comment]
This is fixed

![Uploading Screenshot 2021-06-30 at 6.32.18 PM.png…]()
